baseURL = 'https://blog.junjie.pro/'
locale = 'zh-CN'
title = '原俊杰的博客'
hasCJKLanguage = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"

[params]
  name = '原俊杰'
  bio = '主机全面启动，核心就绪，本舰待命中。'

  github = 'junjieyuan'
  rss = true
